config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("admin/", admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

# Specifying a namespace in urls.py(config)
app_name = "core"

urlpatterns = [
    #HomeView is Class. so return use "as_view" for return view shape
    path("",room_views.HomeView.as_view(), name="home"),
]

rooms/urls.py
from django.urls import path
from . import views

# Specifying a namespace in urls.py(config)
app_name = "rooms"

# URL Dispatcher (like <int:year> ~) : https://docs.djangoproject.com/en/3.1/topics/http/urls/
urlpatterns = [
    path("<int:pk>", views.RoomDetail.as_view(), name="detail"),
    path("search/", views.Search, name="search"),
]

rooms/models.py
from django.db import models
from django.urls import reverse
from django_countries.fields import CountryField
from core import models as core_models
from users import models as user_models

class AbstactItem(core_models.TimeStampedModel):

    """ Abstract Item """

    name = models.CharField(max_length=80)

    """ https://docs.djangoproject.com/en/2.2/topics/db/models/ (About Meta class)"""

    class Meta:
        abstract = True

    def __str__(self):
        return self.name


class RoomType(AbstactItem):

    """ RoomType Models Definition """

    class Meta:
        " verbose_name : Customize name and django plus 's' after that"
        verbose_name = "Room Type"
        " Ordering by created date in AbstarctItem(core_models.TimeStampedModel)"
        ordering = ["created"]


class Amenity(AbstactItem):

    """ Amenity Models Demodelsfinition """

    class Meta:
        " verbose_name_plural : Customize all of name "
        verbose_name_plural = "Amenities"


class Facility(AbstactItem):

    """ Facility Models Definition """

    class Meta:
        verbose_name_plural = "Facilities"


class HouseRule(AbstactItem):

    """ HouseRule Models Definition """

    class Meta:
        verbose_name = "House Rule"


class Photo(core_models.TimeStampedModel):

    """ Photo Models Definition """

    caption = models.CharField(max_length=100)
    file = models.ImageField(upload_to="room_photos")
    " Can definite class for using String. Use this because of Error because python read code from top to bottom "
    room = models.ForeignKey("Room", related_name="photos", on_delete=models.CASCADE)

    def __str__(self):
        return self.caption


class Room(core_models.TimeStampedModel):

    """ Room model custom """

    name = models.CharField(max_length=140)
    description = models.TextField()
    country = CountryField()
    city = models.CharField(max_length=80)
    prices = models.IntegerField()
    address = models.CharField(max_length=140)
    guests = models.IntegerField()
    beds = models.IntegerField()
    bedrooms = models.IntegerField()
    baths = models.IntegerField()
    check_in = models.TimeField()
    check_out = models.TimeField()
    instant_book = models.BooleanField(default=False)
    """ [ForeignKey] Connect to the other models(users models) *import user models* """
    # related_name : customize name (org : room_set [objectname_set])
    host = models.ForeignKey(
        user_models.User, related_name="rooms", on_delete=models.CASCADE
    )
    room_type = models.ForeignKey(
        RoomType, related_name="rooms", on_delete=models.SET_NULL, null=True
    )
    """ ManyToMany is 多:多 Not 1:多 """
    amenity = models.ManyToManyField(Amenity, related_name="rooms", blank=True)
    facility = models.ManyToManyField(Facility, related_name="rooms", blank=True)
    house_rules = models.ManyToManyField(HouseRule, related_name="rooms", blank=True)

    def save(self, *args, **kwargs):
        self.city = str.capitalize(self.city)
        super().save(*args, **kwargs) # Call the real save() method

    def __str__(self):
        return self.name

    # Override Func. "VIEW ON SITE"
    def get_absolute_url(self):
        #from django.urls import reverse
        #app_name(urls.py) / detail : name(urlpatterns) / room.pk : Arguments(pk)
        return reverse("rooms:detail",kwargs = {"pk":self.pk,})


    def total_rating(self):
        all_reviews = self.reviews.all()
        all_rating = 0
        if (len(all_reviews) == 0):
            return 0
        for review in all_reviews:
            all_rating += review.rating_average()
        return round(all_rating / len(all_reviews), 2)

rooms/views.py
from django.utils import timezone
from django.http import Http404
from django.urls import reverse
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from django_countries import countries
from . import models

#Class Based View (CBV)
class HomeView(ListView):
    
    """ HomeView Definition """

    model = models.Room
    # Attributes : https://ccbv.co.uk/projects/Django/2.2/django.views.generic.list/ListView/
    paginate_by = 10
    paginate_orphans = 5
    ordering = "created"
    context_object_name = "rooms"

    # def get_context_data(self, **kwargs):
    #     context = super(HomeView, self).get_context_data(**kwargs)
    #     now = timezone.now()
    #     context["now"] = now
    #     return context

# CBV(Class Based View)
class RoomDetail(DetailView):
    
    """ RoomDetail Definition """
    model = models.Room
    # Attributes : http://ccbv.co.uk/projects/Django/3.0/django.views.generic.detail/DetailView/
    pk_url_kwarg = 'pk'


# FBV(Function Based View)
"""
def room_detail(request, pk):
    # Param "pk" received in rooms/urls.py
    try:
        room = models.Room.objects.get(pk=pk)
        #{'room':room} => content
        return render(request, "rooms/detail.html", {'room':room})
    except models.Room.DoesNotExist:
        #return redirect(reverse("core:home"))
        #return redirect(reverse("rooms:detail",kwargs={"pk":247}))
        #from django.http import Http404
        raise Http404()
"""
#Get countries : https://github.com/SmileyChris/django-countries#the-country-object
def Search(request):
    city = request.GET.get("city","anywhere")
    city = str.capitalize(city)
    country = request.GET.get("country","KR")
    room_type = int(request.GET.get("room_type",0))
    price = int(request.GET.get("price",0))
    guests = int(request.GET.get("guests",0))
    bedrooms = int(request.GET.get("bedrooms",0))
    baths = int(request.GET.get("baths",0))
    beds = int(request.GET.get("beds",0))
    s_amenities = request.GET.get("amenity")
    s_facilities = request.GET.get("facility")
    form = {
        "city":city, 
        "s_country":country, 
        "s_room_type":room_type,
        "price":price,
        "guests":guests,
        "bedrooms":bedrooms,
        "baths":baths,
        "beds":beds,
        "s_amenities":s_amenities,
        "s_facilities":s_facilities,
    }

    room_types = models.RoomType.objects.all()
    amenities = models.Amenity.objects.all()
    facilities = models.Facility.objects.all()
    choices = {
        "countries":countries, 
        "room_types":room_types,
        "amenities":amenities,
        "facilities":facilities,
    }

    return render(
        request, 
        "rooms/search.html", 
        {**form,**choices,},
    )

templates/rooms/detail.html
{% extends "base.html" %}

{% block page_name %}
    Detail
{% endblock page_name %}

{% block content %}
<div>
    <h1>{{room.name}}</h1>
    <h3>{{room.description}}</h3>
</div>
<div>
    <h2>By: {{room.host.username}}
    {% if room.host.superhost %}
        (superhost)    
    {% endif %}
    </h2>
    <h3>Amenities</h3>
    <ul>
    {% for a in room.amenity.all %}
        <li>{{a}}</li>
    {% endfor %}
    </ul>
    <h3>Facilities</h3>
    <ul>
    {% for a in room.facility.all %}
        <li>{{a}}</li>
    {% endfor %}
    </ul>
    <h3>House Rules</h3>
    <ul>
    {% for a in room.house_rules.all %}
        <li>{{a}}</li>
    {% endfor %}
    </ul>
    
</div>
{% endblock %}

templates/rooms/home.html
{% extends "base.html" %}

{% block page_name %}
    Home
{% endblock page_name %}

{% block content %}
    {%for room in page%}
        <h1>{{room.name}} / {{room.prices}}</h1>
    {% endfor %}

    <h5>
        <!-- Use Custom Template tags and filters (https://docs.djangoproject.com/en/2.2/howto/custom-template-tags/) 
        {% if page != 1 %}
            <a href="?page={{page|add:-1}}">Prev</a>
        {% endif %}
        -->
        
        <!-- Pagination -->
        {% if page.has_previous %}
            <a href="?page={{page.previous_page_number}}">Prev</a>
        {% endif %}
        page {{page.number}} of {{page.paginator.num_pages}} 
        {% if page.has_next %}
            <a href="?page={{page.next_page_number}}">Next</a> 
        {% endif %}
        
    </h5>

{% endblock content %}

templates/rooms/room_detail.html
{% extends "base.html" %}

{% block page_title %}
    {{room.name}}
{% endblock page_title %}

{% block content %}
<div>
    <!-- DetailView automatically set object name to models name(room). default : object -->
    <h1>{{object.name}}</h1>
    <h3>{{room.description}}</h3>
</div>
<div>
    <h2>By: {{room.host.username}}
    {% if room.host.superhost %}
        (superhost)    
    {% endif %}
    </h2>
    <h3>Amenities</h3>
    <ul>
    {% for a in room.amenity.all %}
        <li>{{a}}</li>
    {% endfor %}
    </ul>
    <h3>Facilities</h3>
    <ul>
    {% for a in room.facility.all %}
        <li>{{a}}</li>
    {% endfor %}
    </ul>
    <h3>House Rules</h3>
    <ul>
    {% for a in room.house_rules.all %}
        <li>{{a}}</li>
    {% endfor %}
    </ul>
    
</div>
{% endblock %}

templates/rooms/room_list.html
{% extends "base.html" %}

{% block page_title %}
    Home
{% endblock page_title %}

{% block content %}

    <!-- Automatically get List as named "object_list" -->
    <!-- Set List name to "rooms" (context_object_name) -->
    {%for room in rooms%}
        <h3>
            <!-- rooms : app_name(urls.py) / detail : name(urlpatterns) / room.pk : Arguments(pk) -->
            <a href = "{% url "rooms:detail" room.pk %}">
                {{room.name}} / ${{room.prices}}
            </a>
        </h3>
    {% endfor %}

    <h5>
        <!-- Use Custom Template tags and filters (https://docs.djangoproject.com/en/2.2/howto/custom-template-tags/) 
        {% if page != 1 %}
            <a href="?page={{page|add:-1}}">Prev</a>
        {% endif %}
        -->
        
        <!-- Pagination -->
        <!-- Pagination a ListView : https://docs.djangoproject.com/en/3.1/topics/pagination/ -->
        {% if page_obj.has_previous %}
            <a href="?page={{page_obj.previous_page_number}}">Prev</a>
        {% endif %}
        page {{page_obj.number}} of {{page_obj.paginator.num_pages}} 
        {% if page_obj.has_next %}
            <a href="?page={{page_obj.next_page_number}}">Next</a> 
        {% endif %}
        
    </h5>

{% endblock content %}

templates/rooms/search.html
{% extends "base.html" %}

{% block page_title %}
    Search
{% endblock page_title %}

<!--To hide search-bar on search page-->
{% block search-bar %}
{% endblock search-bar %}

{% block content %}
    <h2>Search!</h2>
    <form method="get" action="{% url "rooms:search" %}">
        <div>
            <label for="city">City</label>
            <input value="{{city}}" name="city" placeholder="Search by City"/>
        </div>
        <div>
            <label for="country">Country</label>
            <select id="country" name="country">
                {% for country in countries %}
                    <option value="{{country.code}}" {% if country.code == s_country %}selected{% endif %}>{{country.name}}</option>
                {% endfor %}
            </select>
        </div>
        <div>
            <label for="room_type">Room Type</label>
            <select id="room_type" name="room_type">
                <option value="0" {% if s_room_type == 0 %}selected{% endif %}>Any Kind</option>
                {% for room_type in room_types %}
                    <option value="{{room_type.pk}}" {% if room_type.pk is s_room_type %}selected{% endif %}>{{room_type.name}}</option>
                {% endfor %}
            </select>
        </div>
        <div>
            <label for="price">Price</label>
            <input type="number" value={{price}} name="price" id="price" placeholder="Price"/>
        </div>
        <div>
            <label for="guests">Guests</label>
            <input type="number" value={{guests}} name="guests" id="guests" placeholder="Guests"/>
        </div>
        <div>
            <label for="bedrooms">Bedrooms</label>
            <input type="number" value={{bedrooms}} name="bedrooms" id="bedrooms" placeholder="Bedrooms"/>
        </div>
        <div>
            <label for="beds">Beds</label>
            <input type="number" value={{beds}} name="beds" id="beds" placeholder="Beds"/>
        </div>
        <div>
            <label for="baths">Baths</label>
            <input type="number" value={{baths}} name="baths" id="baths" placeholder="Baths"/>
        </div>
        <div>
            <h3>Amenities</h3>
            <ul>
            {% for amenity in amenities %}
                <li>
                <label for="a_{{amenity.pk}}">{{amenity.name}}</label>
                <input id="a_{{amenity.pk}}" type="checkbox" name="amenities" value={{amenity.pk}}/>
                </li>
            {% endfor %}
            </ul>
        </div>
        <div>
            <h3>Facilities</h3>
            <ul>
            {% for facility in facilities %}
                <li>
                <label for="f_{{facility.pk}}">{{facility.name}}</label>
                <input id="f_{{facility.pk}}" type="checkbox" name="facilities" value={{faciliy.pk}}/>
                </li>
            {% endfor %}
            </ul>
        </div>
        <button>Search</button>
    </form>
{% endblock content %}